### PR TITLE
Hard-code fix to problem gages

### PR DESCRIPTION
**Pull request by ldecicco-USGS**
image

### CODE REVIEW

**Comment by jread-usgs** [comment]
looks good. Is the gage 4th down from the top a goofy one too earlier than blocked out? looks like it on the nwis page

**Comment by dblodgett-usgs** [comment]
I don't think so. It's this one: https://waterdata.usgs.gov/nwis/uv?site_no=50136400

**Comment by jread-usgs** [comment]
whoops, fifth one down: https://waterdata.usgs.gov/nwis/uv?site_no=50144000

**Comment by dblodgett-usgs** [comment]
Oh , that one's going crazy!

**Pull request merged**
