### PR TITLE
Station Name tool tips.

### PR DESCRIPTION
**Pull request by dblodgett-usgs**
screen shot 2017-09-20 at 12 13 41 pm

```
[1] "Rio Grande de Arecibo below Utuado, PR"             
 [2] "Rio Grande de Arecibo near San Pedro, PR"           
 [3] "Rio Grande de Manati near Morovis, PR"              
 [4] "Rio Grande de Manati at Ciales, PR"                 
 [5] "Rio Grande de Manati at Hwy 2 near Manati, PR"      
 [6] "Rio Cibuco below Corozal, PR"                       
 [7] "Rio Cibuco at Vega Baja, PR"                        
 [8] "Rio de La Plata at Proyecto La Plata, PR"           
 [9] "Rio de La Plata at Comerio, PR"                     
[10] "Rio de La Plata below La Plata Damsite, PR"         
[11] "Rio de La Plata at Hwy 2 near Toa Alta, PR"         
[12] "Rio Piedras at Hato Rey, PR"                        
[13] "Rio Grande de Loiza at Hwy 183 San Lorenzo, PR"     
[14] "Rio Grande de Loiza at Caguas, PR"                  
[15] "Rio Gurabo below El Mango, PR"                      
[16] "Rio Gurabo at Gurabo, PR"                           
[17] "Rio Coamo at Hwy 14 at Coamo, PR"                   
[18] "Rio Cerrillos Abv Lago Cerrillos near Ponce, PR"    
[19] "Rio Portugues near Tibes, PR"                       
[20] "Rio Rosario near Hormigueros, PR"                   
[21] "Rio Guanajibo near Hormigueros, PR"                 
[22] "Rio Grande de Anasco near San Sebastian, PR"        
[23] "Rio Culebrinas at Hwy 404 near Moca, PR"            
[24] "Rio Culebrinas at Margarita Damsite near Aguada, PR"
```

### CODE REVIEW

**Comment by aappling-usgs** [comment]
beautiful!

**Comment by dblodgett-usgs** [comment]
uhh... should we lowercase La ?

**Comment by aappling-usgs** [comment]
ack! yes

**Comment by dblodgett-usgs** [comment]
Done in #47

**Pull request merged**
