### PR TITLE
social media icons + thumbnails

### PR DESCRIPTION
**Pull request by lindsaycarr**
The thumbnail images themselves are temporary and need to be updated, but the infrastructure is there now :)

### CODE REVIEW

**Comment by ldecicco-USGS** [comment]
Marty had added the social icons to the actual `vizlab` package and showed how to do in here:
https://github.com/USGS-VIZLAB/example/blob/master/viz.yaml

If you want to try that workflow, I'd be curious to see if it works for you

**Comment by lindsaycarr** [comment]
Yeah, I can try that

**Comment by lindsaycarr** [comment]
Only thing I don't like is there is no way to customize the URLs for the Twitter and FB links

**Comment by lindsaycarr** [comment]
It's not working for me right out of the gate. I'd like to merge this so it doesn't get too far behind viz.yaml and end up with merge conflicts. I will work on the new way once I've got social media plan stuff done.

**Comment by ldecicco-USGS** [comment]
Sounds good...can you make an issue in `vizlab` do describe what the problem was?

**Pull request merged**
